/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//******************************************************
//Instituto Federal de São Paulo - Campus Sertãozinho
//Disciplina......: M3LPBD
//Programação de Computadores e Dispositivos Móveis
//Aluno...........: Arley Laurindo de Oliveira
//******************************************************
/**
 *
 * 
 *  @author Arley Laurindo de Oliveira
 * Tela: responsavel por : *carregador os dados do banco para uma lista,converter lista de obejtos em lista de strings,enviar dados para o combobox.
 */
 
public class ExcluirDisciplinaTela extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirDisciplina
     */
    
    private TelaPrincipal telaAnterior;
    private ExcluirDisciplinaTela() {
        initComponents();
    }
    
    
    int  item_selecionado_combobox;
    String item_do_vetor_no_combobox;
    String objeto_string;
    public ExcluirDisciplinaTela( TelaPrincipal telaAnterior) {
    
    
    //para chamaro construtor padrao 
    this();
    this.telaAnterior = telaAnterior;
        
    //o combobox precisa ser carregado dentro do construtor, ao invesd do evento e click do mesmo,assim quanto instancia uma janela
    //ele carrega já os dados
    
        DisciplinaDAO pegaTodasAsDisciplinas  = new DisciplinaDAO();
        
        
        /*um laço para pegar os itens de dentro do banco com o metodo carregadisciplinas e o mesmo laço está injetado dentro do combobox,os objetos
        levando em consideracao que, estou transformando os objetos em string e jogando dentro do combobox
        */
        for(int i=0;i<pegaTodasAsDisciplinas.CarregarDisciplinas().size();i++){
            Disciplina disciplina = new Disciplina();
            
            //aqui pegamos uma posicao do arraylist e jogamos dentro de um novo objeto.
            disciplina = pegaTodasAsDisciplinas.CarregarDisciplinas().get(i);
            
            // "caixa_com_disciplinas => é uma string que vai ser adionada dentro do combobox
            String caixa_com_disciplinas = "Id "+disciplina.getId_discplina()+"/"+"Nome "+disciplina.getNome()+", Carga hoarária : "
                    +disciplina.getCarga_horaria()+", Curso "+disciplina.getCurso()+", Vagas "+disciplina.getVagas();
            
            //a cada laço que roda no sistema, um item vai sendo adcionando na lista do combobox
            jComboBox_disciplinas.addItem(caixa_com_disciplinas);
            
            
        }
      
        
        item_selecionado_combobox = jComboBox_disciplinas.getSelectedIndex();
        
        System.out.println("Numero selecionado no combobox "+item_selecionado_combobox);
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_disciplinas = new javax.swing.JComboBox<>();
        bt_excluir_disciplina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Excluir Disciplina");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jComboBox_disciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_disciplinasActionPerformed(evt);
            }
        });

        bt_excluir_disciplina.setText("Excluir");
        bt_excluir_disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir_disciplinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_disciplinas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(bt_excluir_disciplina)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jComboBox_disciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(bt_excluir_disciplina)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(655, 380));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
 telaAnterior.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jComboBox_disciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_disciplinasActionPerformed
        // TODO add your handling code here:
        
       /* 
        item_selecionado_combobox = jComboBox_disciplinas.getSelectedIndex();
        
        
        
        DisciplinaDAO carregarDisciplinas  = new DisciplinaDAO();
       //  carregarDisciplinas.CarregarDisciplinas();
       
        //jComboBox_disciplinas.addItem(carregarDisciplinas.ListarDisciplina());
        carregarDisciplinas.removerDisciplina(item_selecionado_combobox);*/
        
        
    }//GEN-LAST:event_jComboBox_disciplinasActionPerformed

    private void bt_excluir_disciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluir_disciplinaActionPerformed
        
        
        //instanciar classe dao com metodo para excluir, no caso vai passar por paramentro o item selecionado
        DisciplinaDAO carregarDisciplinas  = new DisciplinaDAO();
        
        //item_selecionado é um valor dos itens do combobox e nao do id do objeto no combox
        item_selecionado_combobox = jComboBox_disciplinas.getSelectedIndex();
        
        //depois que temos o item selesciona ou alias o id dele,vamos pegar o tem pelo o id,como no que fiz a baixo.
        objeto_string = jComboBox_disciplinas.getItemAt(item_selecionado_combobox);
        
        //recaptulando no codigo acima eu peguei  o id do combobox e busquei o item dele e joguei numa string
        
        System.out.println("Numero selecionado no combobox "+item_selecionado_combobox);
        System.out.println("Item selecionado no combobox "+objeto_string);
        
        //nessa  variavel estou preparando uma variavel para receber o objeto selesconaod no combobox,e nele realizar o tratamento.
        String numero_String = objeto_string;
         
        /*logo abaixo temos o tratamento onde vamos começar a ler  o inicio da string no caso eu botei para começar apartir da casa 3 que é de onde vai contar
        até o "/" barra, e isso vai gerar uma string com conteudo numerico, restando apenas converter esse conteudo em valor inteiro.*/ 
        int pos = numero_String.indexOf("/");
         //Substring iniciando em 0 até posição do caracter especial
        System.out.println("ver se o metodo funcionou : "+numero_String.substring(3, pos) );
        
        
        String vai_virar_numero = numero_String.substring(3, pos);
        
        System.out.println("String que vai virar numero : " +vai_virar_numero);
        
        //string com valor sendo passada para inteiro
        int id_exclusao =Integer.parseInt(vai_virar_numero);
        
        
       carregarDisciplinas.removerDisciplina(id_exclusao);
        
      
        
        
    }//GEN-LAST:event_bt_excluir_disciplinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirDisciplinaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirDisciplinaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirDisciplinaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirDisciplinaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirDisciplinaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_excluir_disciplina;
    private javax.swing.JComboBox<String> jComboBox_disciplinas;
    // End of variables declaration//GEN-END:variables
}
